### PR TITLE
Switch to carlos-mg89/oauth fork of lusitanian/oauth and add PHP 8.1 to CI

### PR DESCRIPTION
**Pull request by samwilson**

### CODE REVIEW

**Comment by samwilson** [comment]
The errors here are all because the CI test account on Flickr has been removed. I've emailed Flickr asking them if there's a test API service we could hit instead, or if there's some way we could have a test user to use.

If not, I guess integration tests will only be able to run locally. That's not terrible I suppose.

**Comment by samwilson** [comment]
@carlos-mg89 what do you think of this?

I heard back from Flickr, and they said nothing but that I should ask on the API group. I've [done so](https://www.flickr.com/groups/api/discuss/72157721916642419/) but am not hopeful of finding a way to run CI against the API, so for now have added skips for all the tests that fail. This should make it possible to run everything locally, and also get the tests passing in CI. Hardly ideal though.

**Comment by carlos-mg89** [comment]
Oh, that's quite awkward of them. Could you create another API account and replace the one you had with this new one?

I guess this is the only way I can think of to have real integration tests. Otherwise, I'm afraid I cannot see any other viable options to deal with the situation.

**Comment by samwilson** [comment]
Yeah, I did that! This was I think my third account, and it made me wonder what was going on. :-)

At least this way we do get *some* testing.

The other thing I've wondered about is integrating the bits of the oauth library that we need directly into this one, and removing the dependency all together.

**Comment by samwilson** [comment]
I'm keen to switch to this fork, but have asked on the main project about what the status is in general. Would be good if we all moved to the same fork, I think! Makes maintenance easier.

**Comment by carlos-mg89** [comment]
Happy to help @samwilson , if at any moment you need something from me, just let me know.

**Comment by samwilson** [comment]
Okay, all done and version 4.14.3 released.

**Comment by carlos-mg89** [comment]
@samwilson I've done all the changes you mentioned. It's actually been a nice exercise to implement CI tools with Scrutinizer.

You've got the README updated in the Git repository.

**Pull request merged**
