### PR TITLE
Remove deprecated methods

### PR DESCRIPTION
**Pull request by stevenmaguire**
This PR is an attempt to help clean up this package relative to #38 and some general code formatting.

I removed any method that was decorated with the `@deprecated` PHP doc block and a couple that did not have that decoration but were formatted consistently with most of the other decorated methods.

I hope this is helpful! I would love to see a version of this package that is lighter and no longer throws warnings in a PHP >=8.0 environment :)

### CODE REVIEW

**Comment by samwilson** [comment]
Thanks for working on this! Good idea on removing the deprecations, it's definitely about time! This will be a breaking change of course, and so we'll update the major version number.

It looks like you made a bunch of code formatting changes too, which now are failing with phpcs. The `composer test` script should be run, it does everything that CI does.

**Comment by stevenmaguire** [comment]
> It looks like you made a bunch of code formatting changes too, which now are failing with phpcs. The composer test script should be run, it does everything that CI does.

Thanks for the heads up - I did miss that. The linter is passing now. Hopefully that is good news.

**Comment by samwilson** [comment]
Thanks!

There are still masses of formatting changes here though. Are they necessary? I feel like changes should be focused, and if this is about removing deprecations then that's all it should do. Would you mind if we kept this smaller?

Also, if changes such as array spacing or single/double quotes are required, they should be enforced by linter rules.

**Comment by stevenmaguire** [comment]
Sure. I have a habit of running PHP code through some opinionated code cleaning tools. That is where this originally came from.

**Comment by samwilson** [comment]
Great! Thanks for this. There will be a few follow-ups I reckon, before we can release 5.0, but this is the bulk of it!

**Pull request merged**
